### ISSUE TITLE
Sqlite Database using UTF-8 and rows containing accentuated characters are not found

### ISSUE THREAD

**Issue by nilopaim** [neosmart/CppSQLite#6]
My database is encoded as UTF-8. I've several rows that contains strings with accentuated characters (ã, é, í, etc).

A SELECT comand using this strings on the WHERE clause returns no lines.

Code sample:
`	string word = "série"; // Just a sample...

        command += "select ";
	command += "	type, ";
	command += "	originalword, ";
	command += "	id ";
	command += "from ";
	command += "	dict ";
	command += "WHERE ";
	command += "	word = ? ";
	command += "ORDER BY ";
	command += "	id asc ";

	CppSQLite3Statement stmt = db.compileStatement(command.c_str());

	stmt.bind(1, word.c_str());

	CppSQLite3Query t;

	try
	{
		t = stmt.execQuery();
	}
	catch (CppSQLite3Exception& e)
	{`

If "word" have accentuated chars, no lines are returned.

**Comment by super-xiam** [comment]
there maybe something wrong in your code. Is your code-editor encoding with 'utf8'?

**Comment by mqudsi** [comment]
The legacy CppSqlite code is not null-safe, meaning strings may be (and are) truncated upon encountering an embedded null. However, the unicode spec purposely does not use null bytes in UTF-8, so that shouldn't be a problem.
